name: Deploy to Nest

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy and Restart read,ef, on Nest via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: hackclub.app
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/readmefm
            git pull
            npm ci || exit 1
            systemctl --user restart readmefm.service || exit 1
